In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Prade\Downloads\archive (1)\paysim.zip.csv")

In [2]:
print("shape:",df.shape)

shape: (6362620, 11)

In [3]:
print("columns",df.columns.tolist())

columns ['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig', 'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud', 'isFlaggedFraud']

In [4]:
print("datatypes:",df.dtypes)

datatypes: step                int64
type               object
amount            float64
nameOrig           object
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest           object
oldbalanceDest    float64
newbalanceDest    float64
isFraud             int64
isFlaggedFraud      int64
dtype: object

In [5]:
print("\nFirst 5 rows:",df.head())

First 5 rows:    step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72
2     1  TRANSFER    181.00  C1305486145          181.0            0.00
3     1  CASH_OUT    181.00   C840083671          181.0            0.00
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud
0  M1979787155             0.0             0.0        0               0
1  M2044282225             0.0             0.0        0               0
2   C553264065             0.0             0.0        1               0
3    C38997010         21182.0             0.0        1               0
4  M1230701703             0.0             0.0        0               0

In [6]:
print("Missing_values",df.isnull().sum())

Missing_values step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [7]:
print("Duplicate_Values",df.duplicated().sum())

Duplicate_Values 0

In [8]:
print("Fraud Distribution:",df["isFraud"].value_counts())

Fraud Distribution: isFraud
0    6354407
1       8213
Name: count, dtype: int64

In [9]:
print("Flagged Fraud Distribution:",df["isFlaggedFraud"].value_counts())

Flagged Fraud Distribution: isFlaggedFraud
0    6362604
1         16
Name: count, dtype: int64

In [10]:
print("Transaction Types",df["type"].value_counts())

Transaction Types type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64

In [11]:
df["amount"].describe()

count    6.362620e+06
mean     1.798619e+05
std      6.038582e+05
min      0.000000e+00
25%      1.338957e+04
50%      7.487194e+04
75%      2.087215e+05
max      9.244552e+07
Name: amount, dtype: float64

In [12]:
df.groupby("type")["isFraud"].sum()

type
CASH_IN        0
CASH_OUT    4116
DEBIT          0
PAYMENT        0
TRANSFER    4097
Name: isFraud, dtype: int64

In [13]:
#Fraud rate by transaction type
fraud_rate=(df.groupby("type")["isFraud"].mean().mul(100).round(2).sort_values(ascending=False))
fraud_rate

type
TRANSFER    0.77
CASH_OUT    0.18
CASH_IN     0.00
DEBIT       0.00
PAYMENT     0.00
Name: isFraud, dtype: float64

In [14]:
#Fraud amount by transaction type
fraud_amount=df[df["isFraud"]==1].groupby("type")["amount"].sum().sort_values(ascending=False)
fraud_amount

type
TRANSFER    6.067213e+09
CASH_OUT    5.989202e+09
Name: amount, dtype: float64

In [15]:
#Fraud Rate by transaction amount
bins=[0,10000,50000,100000,500000,float("inf")]
labels=["0-10k","10k-50k","50k-100k","100k-500k","500k+"]
df["amount_range"]=pd.cut(df["amount"],bins=bins,labels=labels,include_lowest=True)
fraud_by_amount=(df.groupby("amount_range",observed=True)["isFraud"].mean().mul(100).round(2))
fraud_by_amount

amount_range
0-10k        0.02
10k-50k      0.05
50k-100k     0.09
100k-500k    0.11
500k+        1.14
Name: isFraud, dtype: float64

In [16]:
#fraud trend over time
fraud_by_step=(df.groupby("step")["isFraud"].sum().sort_values(ascending=False))
print(fraud_by_step.head(10))

step
212    40
523    30
387    28
501    28
730    28
425    28
249    28
398    26
160    26
406    24
Name: isFraud, dtype: int64

In [17]:
step_212=df[(df["step"]==212)&(df["isFraud"]==1)]
step_212

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,amount_range
2726958,212,TRANSFER,555574.92,C1651626047,555574.92,0.00,C1496518496,0.00,0.00,1,0,500k+
2726959,212,CASH_OUT,555574.92,C857225298,555574.92,0.00,C1399829166,4271280.57,4826855.50,1,0,500k+
2729493,212,TRANSFER,927620.44,C533316597,927620.44,0.00,C762597253,0.00,0.00,1,0,500k+
2729494,212,CASH_OUT,927620.44,C36961525,927620.44,0.00,C1313128046,0.00,927620.44,1,0,500k+
2729564,212,TRANSFER,94261.84,C1350141268,94261.84,0.00,C1676513288,0.00,0.00,1,0,50k-100k
2729565,212,CASH_OUT,94261.84,C1967440853,94261.84,0.00,C1496631599,112303.11,206564.95,1,0,50k-100k
2730385,212,TRANSFER,3640983.71,C2080183074,3640983.71,0.00,C367657984,0.00,0.00,1,0,500k+
2730386,212,CASH_OUT,3640983.71,C1978111036,3640983.71,0.00,C105806122,409527.87,4050511.58,1,0,500k+
2730590,212,TRANSFER,31593.95,C1956751505,31593.95,0.00,C1580974524,0.00,0.00,1,0,10k-50k
2730591,212,CASH_OUT,31593.95,C1513967343,31593.95,0.00,C1815135338,428186.97,459780.93,1,0,10k-50k
2736440,212,TRANSFER,10000000.00,C1531278091,34953893.08,24953893.08,C972530514,0.00,0.00,1,0,500k+
2736441,212,CASH_OUT,10000000.00,C1041060645,10000000.00,0.00,C1784785490,766422.52,10656162.27,1,0,500k+
2736442,212,TRANSFER,10000000.00,C217654973,24953893.08,14953893.08,C167868594,0.00,0.00,1,0,500k+
2736443,212,CASH_OUT,10000000.00,C1251439451,10000000.00,0.00,C290459952,0.00,10000000.00,1,0,500k+
2736444,212,TRANSFER,10000000.00,C976919593,14953893.08,4953893.08,C769483130,0.00,0.00,1,0,500k+
2736445,212,CASH_OUT,10000000.00,C1853514800,10000000.00,0.00,C591314687,0.00,10000000.00,1,0,500k+
2736446,212,TRANSFER,4953893.08,C728984460,4953893.08,4953893.08,C639921569,0.00,0.00,1,1,500k+
2736447,212,CASH_OUT,0.00,C1510987794,0.00,0.00,C1696624817,0.00,0.00,1,0,0-10k
2736953,212,TRANSFER,296699.39,C1746633930,296699.39,0.00,C1032143722,0.00,0.00,1,0,100k-500k
2736954,212,CASH_OUT,296699.39,C724206684,296699.39,0.00,C1519890432,162636.95,459336.34,1,0,100k-500k
2739882,212,TRANSFER,1220.80,C192629341,1220.80,0.00,C711485958,0.00,0.00,1,0,0-10k
2739883,212,CASH_OUT,1220.80,C248395903,1220.80,0.00,C154068331,338688.89,339909.69,1,0,0-10k
2740543,212,TRANSFER,36035.11,C1338159838,36035.11,0.00,C18838691,0.00,0.00,1,0,10k-50k
2740544,212,CASH_OUT,36035.11,C1218258377,36035.11,0.00,C1181119627,0.00,36035.11,1,0,10k-50k
2741558,212,TRANSFER,362988.52,C1442171840,362988.52,0.00,C1053252672,0.00,0.00,1,0,100k-500k
2741559,212,CASH_OUT,362988.52,C739877872,362988.52,0.00,C1957802478,2158316.76,2521305.27,1,0,100k-500k
2744220,212,TRANSFER,1434440.31,C1722259172,1434440.31,0.00,C715201096,0.00,0.00,1,0,500k+
2744221,212,CASH_OUT,1434440.31,C886007554,1434440.31,0.00,C1581407467,0.00,1434440.31,1,0,500k+
2752774,212,TRANSFER,1947807.58,C1501311535,1947807.58,0.00,C37561886,0.00,0.00,1,0,500k+
2752775,212,CASH_OUT,1947807.58,C997675082,1947807.58,0.00,C99537162,149.00,1947956.58,1,0,500k+
2753224,212,TRANSFER,5131896.17,C226207762,5131896.17,0.00,C290920701,0.00,0.00,1,0,500k+
2753225,212,CASH_OUT,5131896.17,C2124387698,5131896.17,0.00,C1009747499,302942.16,5434838.33,1,0,500k+
2754077,212,TRANSFER,165925.37,C1647539449,165925.37,0.00,C823304803,0.00,0.00,1,0,100k-500k
2754078,212,CASH_OUT,165925.37,C692577910,165925.37,0.00,C36794671,3390123.05,3556048.41,1,0,100k-500k
2754366,212,TRANSFER,704328.29,C1183135461,704328.29,0.00,C1446253105,0.00,0.00,1,0,500k+
2754367,212,CASH_OUT,704328.29,C247084608,704328.29,0.00,C359887652,0.00,704328.29,1,0,500k+
2755032,212,TRANSFER,362631.05,C1251759902,362631.05,0.00,C75355732,0.00,0.00,1,0,100k-500k
2755033,212,CASH_OUT,362631.05,C1776783873,362631.05,0.00,C1114102107,31491.56,394122.61,1,0,100k-500k
2756585,212,TRANSFER,3996798.71,C1093407378,3996798.71,0.00,C1069699196,0.00,0.00,1,0,500k+
2756586,212,CASH_OUT,3996798.71,C1817956756,3996798.71,0.00,C362023079,4511245.41,8508044.12,1,0,500k+

In [18]:
#fraud rate by time period
fraud_rate_by_step=(df.groupby("step")["isFraud"].mean().mul(100).round(2).sort_values(ascending=False))
fraud_rate_by_step

step
743    100.00
533    100.00
269    100.00
268    100.00
568    100.00
        ...
331      0.01
139      0.01
252      0.01
545      0.00
347      0.00
Name: isFraud, Length: 743, dtype: float64

In [19]:
time_analysis=(df.groupby("step").agg(total_transactions=("isFraud","count"),fraud_transactions=("isFraud","sum")))
time_analysis

      total_transactions  fraud_transactions
step
1                   2708                  16
2                   1014                   8
3                    552                   4
4                    565                  10
5                    665                   6
...                  ...                 ...
739                   10                  10
740                    6                   6
741                   22                  22
742                   14                  14
743                    8                   8

[743 rows x 2 columns]

In [20]:
time_analysis["fraud_rate"]=(time_analysis["fraud_transactions"]/time_analysis["total_transactions"]*100).round(2)
time_analysis

      total_transactions  fraud_transactions  fraud_rate
step
1                   2708                  16        0.59
2                   1014                   8        0.79
3                    552                   4        0.72
4                    565                  10        1.77
5                    665                   6        0.90
...                  ...                 ...         ...
739                   10                  10      100.00
740                    6                   6      100.00
741                   22                  22      100.00
742                   14                  14      100.00
743                    8                   8      100.00

[743 rows x 3 columns]

In [21]:
time_analysis=time_analysis[time_analysis["total_transactions"]>=100].sort_values("fraud_rate",ascending=False)
time_analysis

      total_transactions  fraud_transactions  fraud_rate
step
578                  269                  20        7.43
195                  141                  10        7.09
436                  248                  16        6.45
716                  140                   8        5.71
531                  250                  14        5.60
...                  ...                 ...         ...
331                40186                   6        0.01
20                 40625                   4        0.01
252                35590                   2        0.01
545                 3562                   0        0.00
347                30222                   0        0.00

[402 rows x 3 columns]

In [22]:
#identify high risk transaction types and amounts together
fraud_type_amount=((df.groupby(["type","amount_range"],observed=True))["isFraud"].mean().mul(100).round(2).sort_values(ascending=False))
fraud_type_amount.head(10)

type      amount_range
CASH_OUT  500k+           3.61
TRANSFER  0-10k           2.15
          10k-50k         1.53
          50k-100k        1.07
          500k+           0.74
          100k-500k       0.63
CASH_OUT  0-10k           0.20
          10k-50k         0.12
          50k-100k        0.09
          100k-500k       0.09
Name: isFraud, dtype: float64

In [23]:
fraud_amount_by_account=(df[df["isFraud"]==1].groupby("nameOrig")["amount"].sum().sort_values(ascending=False))
fraud_amount_by_account.head(10)

nameOrig
C99979309      10000000.0
C327855497     10000000.0
C315149365     10000000.0
C313051938     10000000.0
C1596180537    10000000.0
C298387535     10000000.0
C292642955     10000000.0
C1111699947    10000000.0
C1110953726    10000000.0
C291823113     10000000.0
Name: amount, dtype: float64

In [24]:
fraud_account_details=(df[df["isFraud"]==1].groupby("nameOrig").agg(fraud_transactions=("isFraud","sum"),total_fraud_amount=("amount","sum")))
fraud_account_details.sort_values("total_fraud_amount",ascending=False).head(10)

             fraud_transactions  total_fraud_amount
nameOrig
C99979309                     1          10000000.0
C327855497                    1          10000000.0
C315149365                    1          10000000.0
C313051938                    1          10000000.0
C1596180537                   1          10000000.0
C298387535                    1          10000000.0
C292642955                    1          10000000.0
C1111699947                   1          10000000.0
C1110953726                   1          10000000.0
C291823113                    1          10000000.0

In [25]:
fraud_receiver=(df[df["isFraud"]==1].groupby("nameDest").agg(total_fraud_amount=("amount","sum"),fraud_transactions=("isFraud","sum")))
fraud_receiver.sort_values("total_fraud_amount",ascending=False).head(10)

             total_fraud_amount  fraud_transactions
nameDest
C668046170          10160088.68                   2
C1630566944         10000000.00                   1
C666339947          10000000.00                   1
C1590217660         10000000.00                   1
C1595458981         10000000.00                   1
C1056895901         10000000.00                   1
C650095152          10000000.00                   1
C1614528665         10000000.00                   1
C1622860679         10000000.00                   1
C1054420449         10000000.00                   1

In [26]:
fraud_receivers=df[df["isFraud"]==1]["nameDest"]
print("Total_Fradualant_Transactions:",len(fraud_receivers))
print("Unique_receiver_accounts:",fraud_receivers.nunique())

Total_Fradualant_Transactions: 8213
Unique_receiver_accounts: 8169

In [27]:
#check suspicious balance changes
df["expected_new_balance"]=(df["oldbalanceOrg"]-df["amount"])
df["balance_difference"]=(df["newbalanceOrig"]-df["expected_new_balance"])
print(df[["oldbalanceOrg","amount","newbalanceOrig","expected_new_balance","balance_difference"]].head(10))

   oldbalanceOrg    amount  newbalanceOrig  expected_new_balance  \
0      170136.00   9839.64       160296.36             160296.36
1       21249.00   1864.28        19384.72              19384.72
2         181.00    181.00            0.00                  0.00
3         181.00    181.00            0.00                  0.00
4       41554.00  11668.14        29885.86              29885.86
5       53860.00   7817.71        46042.29              46042.29
6      183195.00   7107.77       176087.23             176087.23
7      176087.23   7861.64       168225.59             168225.59
8        2671.00   4024.36            0.00              -1353.36
9       41720.00   5337.77        36382.23              36382.23

   balance_difference
0        0.000000e+00
1        0.000000e+00
2        0.000000e+00
3        0.000000e+00
4        0.000000e+00
5        0.000000e+00
6        0.000000e+00
7        0.000000e+00
8        1.353360e+03
9        7.275958e-12

In [28]:
largest_balance_difference=(df[["oldbalanceOrg","amount","newbalanceOrig","expected_new_balance","balance_difference"]].sort_values("balance_difference",ascending=False))
print(largest_balance_difference.head(20))

         oldbalanceOrg       amount  newbalanceOrig  expected_new_balance  \
3686583           0.00  92445516.64             0.0          -92445516.64
4060598           0.00  73823490.36             0.0          -73823490.36
4146397           0.00  71172480.42             0.0          -71172480.42
3946920           0.00  69886731.30             0.0          -69886731.30
3911956           0.00  69337316.27             0.0          -69337316.27
3937152           0.00  67500761.29             0.0          -67500761.29
4105338           0.00  66761272.21             0.0          -66761272.21
3892529           0.00  64234448.19             0.0          -64234448.19
3991638           0.00  63847992.58             0.0          -63847992.58
4143801           0.00  63294839.63             0.0          -63294839.63
4076755           0.00  62785416.91             0.0          -62785416.91
4143417           0.00  61733761.65             0.0          -61733761.65
3682190           0.00  60965275.64             0.0          -60965275.64
3934249           0.00  60642003.00             0.0          -60642003.00
3733545           0.00  60154456.05             0.0          -60154456.05
3859607           0.00  59579503.33             0.0          -59579503.33
3684267           0.00  58944752.64             0.0          -58944752.64
4106481           0.00  58318373.20             0.0          -58318373.20
4138815       42228.75  57787800.93             0.0          -57745572.18
3801347           0.00  57436619.46             0.0          -57436619.46

         balance_difference
3686583         92445516.64
4060598         73823490.36
4146397         71172480.42
3946920         69886731.30
3911956         69337316.27
3937152         67500761.29
4105338         66761272.21
3892529         64234448.19
3991638         63847992.58
4143801         63294839.63
4076755         62785416.91
4143417         61733761.65
3682190         60965275.64
3934249         60642003.00
3733545         60154456.05
3859607         59579503.33
3684267         58944752.64
4106481         58318373.20
4138815         57745572.18
3801347         57436619.46

In [29]:
df["balance_mismatch"]=(df["balance_difference"].abs()>1)
df["balance_mismatch"]

0          False
1          False
2          False
3          False
4          False
           ...
6362615    False
6362616    False
6362617    False
6362618    False
6362619    False
Name: balance_mismatch, Length: 6362620, dtype: bool

In [30]:
balance_fraud_rate=(df.groupby("balance_mismatch")["isFraud"].mean().mul(100).round(2))
balance_fraud_rate

balance_mismatch
False    0.6
True     0.0
Name: isFraud, dtype: float64

In [31]:
flagged_analysis=pd.crosstab(df["isFlaggedFraud"],df["isFraud"])
flagged_analysis

isFraud               0     1
isFlaggedFraud
0               6354407  8197
1                     0    16

In [32]:
#transaction types that are mostly liked to be fraud
flagged_by_type=df[df["isFlaggedFraud"]==1].groupby("type").size().sort_values(ascending=False)
flagged_by_type

type
TRANSFER    16
dtype: int64

In [33]:
transfer_analysis=(df[df["type"]=="TRANSFER"].groupby("isFraud")["amount"].agg(["count","mean","median","max"]).round(2))
transfer_analysis

          count        mean     median          max
isFraud
0        528812   906229.01  486521.91  92445516.64
1          4097  1480891.67  445705.76  10000000.00

In [34]:
df["balance_used_pct"]=((df["amount"]/df["oldbalanceOrg"].replace(0,float("nan")))*100)
df["balance_used_pct"]

0            5.783397
1            8.773495
2          100.000000
3          100.000000
4           28.079463
              ...
6362615    100.000000
6362616    100.000000
6362617    100.000000
6362618    100.000000
6362619    100.000000
Name: balance_used_pct, Length: 6362620, dtype: float64

In [35]:
transfer_balance_analysis=(df[df["type"]=="TRANSFER"].groupby("isFraud")["balance_used_pct"].agg(["count","mean","median","max"]).round(2))
transfer_balance_analysis

          count      mean   median           max
isFraud
0        246033  76296.57  1622.55  1.854643e+08
1          4093     98.54   100.00  1.550300e+02

In [36]:
fraud_balance_usage=(df[(df["type"]=="TRANSFER")&(df["isFraud"]==1)])
print("Fraudulent_transfers:",len(fraud_balance_usage))
print("used 100% or more:",(fraud_balance_usage["balance_used_pct"]>=100).sum())

Fraudulent_transfers: 4097
used 100% or more: 3944

In [37]:
fraud_balance_pct=((fraud_balance_usage["balance_used_pct"]>=100).sum()/len(fraud_balance_usage)*100)
print("Percentage:",round(fraud_balance_pct,2),"%")

Percentage: 96.27 %

In [38]:
zero_balance_analysis=(df.groupby(df["newbalanceOrig"]==0)["isFraud"].agg(["count","mean","sum"]))
zero_balance_analysis

                  count      mean   sum
newbalanceOrig
False           2753054  0.000058   160
True            3609566  0.002231  8053

In [39]:
zero_balance_analysis["fraud_rate"]=(zero_balance_analysis["mean"]*100).round(2)
zero_balance_analysis

                  count      mean   sum  fraud_rate
newbalanceOrig
False           2753054  0.000058   160        0.01
True            3609566  0.002231  8053        0.22

In [40]:
repeated_fraud_senders=(df[df["isFraud"]==1].groupby("nameOrig").size().sort_values(ascending=False))
repeated_fraud_senders[repeated_fraud_senders > 1].head(10)

Series([], dtype: int64)

In [41]:
fraud_zero_balance=pd.crosstab(df["isFraud"],df["newbalanceOrig"]==0)
fraud_zero_balance

newbalanceOrig    False    True
isFraud
0               2752894  3601513
1                   160     8053

In [42]:
zero_balance_by_type=pd.crosstab([df["type"],df["isFraud"]],df["newbalanceOrig"]==0)
zero_balance_by_type

newbalanceOrig      False    True
type     isFraud
CASH_IN  0        1399284        0
CASH_OUT 0         252288  1981096
         1              1     4115
DEBIT    0          29646    11786
PAYMENT  0        1050371  1101124
TRANSFER 0          21305   507507
         1            159     3938

In [43]:
fraud_amount_analysis=(df[df["isFraud"]==1].groupby("type")["amount"].agg(["count","sum","mean","median","max"]).sort_values("sum",ascending=False).round(2))
fraud_amount_analysis

          count           sum        mean     median         max
type
TRANSFER   4097  6.067213e+09  1480891.67  445705.76  10000000.0
CASH_OUT   4116  5.989202e+09  1455102.59  435516.90  10000000.0

In [47]:
fraud_sender_analysis=(df[df["isFraud"]==1].groupby("nameOrig")["amount"].agg(["count","sum","mean"]).sort_values("sum",ascending=False).head(10).round(2))
fraud_sender_analysis

             count         sum        mean
nameOrig
C99979309        1  10000000.0  10000000.0
C327855497       1  10000000.0  10000000.0
C315149365       1  10000000.0  10000000.0
C313051938       1  10000000.0  10000000.0
C1596180537      1  10000000.0  10000000.0
C298387535       1  10000000.0  10000000.0
C292642955       1  10000000.0  10000000.0
C1111699947      1  10000000.0  10000000.0
C1110953726      1  10000000.0  10000000.0
C291823113       1  10000000.0  10000000.0

In [48]:
#compare fraud vs normal transaction
distribution_amount=df.groupby("isFraud")["amount"].quantile([0.25,0.50,0.75,0.90,0.99]).unstack().round(2)
distribution_amount

              0.25       0.50        0.75        0.90         0.99
isFraud
0         13368.40   74684.72   208364.76   364373.44   1586064.17
1        127091.33  441423.44  1517771.48  4521723.51  10000000.00

In [54]:
balance_pattern=(df.groupby(["type","isFraud"]).agg(total_transactions=("isFraud","count"),
                                                   zero_balance_transactions=("newbalanceOrig",lambda x:(x==0).sum())).reset_index())
balance_pattern

       type  isFraud  total_transactions  zero_balance_transactions
0   CASH_IN        0             1399284                          0
1  CASH_OUT        0             2233384                    1981096
2  CASH_OUT        1                4116                       4115
3     DEBIT        0               41432                      11786
4   PAYMENT        0             2151495                    1101124
5  TRANSFER        0              528812                     507507
6  TRANSFER        1                4097                       3938

In [58]:
balance_pattern["zero_balance_pct"]=(balance_pattern["zero_balance_transactions"]/balance_pattern["total_transactions"]*100).round(2)
balance_pattern

,type,isFraud,total_transactions,zero_balance_transactions,zero_balance_pct
0,CASH_IN,0,1399284,0,0.00
1,CASH_OUT,0,2233384,1981096,88.70
2,CASH_OUT,1,4116,4115,99.98
3,DEBIT,0,41432,11786,28.45
4,PAYMENT,0,2151495,1101124,51.18
5,TRANSFER,0,528812,507507,95.97
6,TRANSFER,1,4097,3938,96.12

In [59]:
fraud_summary=df.groupby("isFraud").agg(total_transactions=("isFraud","count"),
                                        total_amount=("amount","sum"),
                                        average_amount=("amount","mean")).round(2)
fraud_summary

         total_transactions  total_amount  average_amount
isFraud
0                   6354407  1.132337e+12       178197.04
1                      8213  1.205642e+10      1467967.30

In [67]:
total_transactions=len(df)
fraud_transactions=df["isFraud"].sum()
normal_transactions=total_transactions-fraud_transactions
fraud_rate=fraud_transactions/total_transactions*100
fraud_amount=df.loc[df["isFraud"]==1,"amount"].sum()

print("total_transactions:",total_transactions)
print("fraud_transactions:",fraud_transactions)
print("normal_transactions:",normal_transactions)
print("fraud_rate:",round(fraud_rate,4),"%")
print("total_amount_involved_in_fraud:",round(fraud_amount,2))

total_transactions: 6362620
fraud_transactions: 8213
normal_transactions: 6354407
fraud_rate: 0.1291 %
total_amount_involved_in_fraud: 12056415427.84

In [68]:
df.to_csv("fraud_detection_cleaned.csv",index=False)